
GET http://localhost:3000/api/post?wt=エンジニア
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjAyY2RkYmI3ODhkNzEyOWRjMDUwYyIsImlhdCI6MTcyMjgyMTkwNywiZXhwIjoxNzIyOTA4MzA3fQ.eN6gwWGYxp2kJTfuXrMvXBudcscAG9KN_QfEe3Pi8NI
###

GET http://localhost:3000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDFjNWEyOTVjOTkwMTMwNDliNzY4MCIsImlhdCI6MTcyMjU2MzMxMCwiZXhwIjoxNzIyNjQ5NzEwfQ.uWNCXs23NURsU7sh1P1PD7lR_bihm7zf6T46sayLuuA

###
DELETE http://localhost:3000/api/admin/category?id=66ac43e4d98a83e38bbc9cdc
Content-Type: application/json
Authorization: "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDFjNWEyOTVjOTkwMTMwNDliNzY4MCIsImlhdCI6MTcyMjU2MzMxMCwiZXhwIjoxNzIyNjQ5NzEwfQ.uWNCXs23NURsU7sh1P1PD7lR_bihm7zf6T46sayLuuA

{
    "name":"eeee"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username":"hoangloc",
    "password":"123456"

}

###
