import Header from "@/component/header";
import SearchTool from "@/component/searchTool";
import type { Metadata } from "next";
import { Noto_Sans_Javanese } from "next/font/google";
import "../style/global.css"
import '../style/global_copy.css'
import '../style/component.css'
import '../style/theme.css'
import Footer from "@/component/footer";

const inter = Noto_Sans_Javanese({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Build your career",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " scrollbar"}>
        {children}
      </body>
    </html>
  );
}
