import Header from "@/component/header";
import type { Metadata } from "next";
import Footer from "@/component/footer";

export const metadata: Metadata = {
  title: "Build your career",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <main style={{ maxWidth: "1600px", margin: "0 auto" }}>
        {children}
      </main>
      <Footer />
    </div>
  );
}
